// Mocks generated by Mockito 5.4.4 from annotations
// in ecotrap/test/features/files/presentation/bloc/files_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ecotrap/features/files/domain/entities/file_entity.dart' as _i5;
import 'package:ecotrap/features/files/domain/repositories/files_repository.dart'
    as _i2;
import 'package:ecotrap/features/files/domain/usecases/download_file.dart'
    as _i6;
import 'package:ecotrap/features/files/domain/usecases/get_files.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFilesRepository_0 extends _i1.SmartFake
    implements _i2.FilesRepository {
  _FakeFilesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetFiles].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFiles extends _i1.Mock implements _i3.GetFiles {
  MockGetFiles() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FilesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFilesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FilesRepository);

  @override
  _i4.Future<List<_i5.FileEntity>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<List<_i5.FileEntity>>.value(<_i5.FileEntity>[]),
      ) as _i4.Future<List<_i5.FileEntity>>);
}

/// A class which mocks [DownloadFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadFile extends _i1.Mock implements _i6.DownloadFile {
  MockDownloadFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FilesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFilesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.FilesRepository);

  @override
  _i4.Future<String> call(
    String? fileName,
    dynamic Function(double)? onProgress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            fileName,
            onProgress,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #call,
            [
              fileName,
              onProgress,
            ],
          ),
        )),
      ) as _i4.Future<String>);
}
