// Mocks generated by Mockito 5.4.4 from annotations
// in ecotrap/test/features/wifi/domain/usecases/save_wifi_network_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ecotrap/core/errors/failures.dart' as _i5;
import 'package:ecotrap/features/wifi/domain/entities/wifi_network.dart' as _i6;
import 'package:ecotrap/features/wifi/domain/repositories/wifi_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WiFiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWiFiRepository extends _i1.Mock implements _i3.WiFiRepository {
  MockWiFiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WiFiNetwork>>> getWiFiNetworks({
    required int? page,
    required int? pageSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWiFiNetworks,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WiFiNetwork>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WiFiNetwork>>(
          this,
          Invocation.method(
            #getWiFiNetworks,
            [],
            {
              #page: page,
              #pageSize: pageSize,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WiFiNetwork>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>> getWiFiNetworkById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWiFiNetworkById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>>.value(
            _FakeEither_0<_i5.Failure, _i6.WiFiNetwork>(
          this,
          Invocation.method(
            #getWiFiNetworkById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>> saveWiFiNetwork({
    required String? ssid,
    required String? password,
    String? bssid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWiFiNetwork,
          [],
          {
            #ssid: ssid,
            #password: password,
            #bssid: bssid,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>>.value(
            _FakeEither_0<_i5.Failure, _i6.WiFiNetwork>(
          this,
          Invocation.method(
            #saveWiFiNetwork,
            [],
            {
              #ssid: ssid,
              #password: password,
              #bssid: bssid,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>> updateWiFiNetwork({
    required String? id,
    required String? ssid,
    required String? password,
    String? bssid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWiFiNetwork,
          [],
          {
            #id: id,
            #ssid: ssid,
            #password: password,
            #bssid: bssid,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>>.value(
            _FakeEither_0<_i5.Failure, _i6.WiFiNetwork>(
          this,
          Invocation.method(
            #updateWiFiNetwork,
            [],
            {
              #id: id,
              #ssid: ssid,
              #password: password,
              #bssid: bssid,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WiFiNetwork>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteWiFiNetwork(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWiFiNetwork,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteWiFiNetwork,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTotalCount() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalCount,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getTotalCount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);
}
