# Memoria para Gradle
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Android
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# ✅ Configurar Java 17 (ajusta la ruta según tu instalación)
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio1\\jbr

# R8 Full Mode para releases
android.enableR8.fullMode=true