// Mocks generated by Mockito 5.4.4 from annotations
// in ecotrap/test/features/wifi/presentation/bloc/wifi_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ecotrap/core/errors/failures.dart' as _i6;
import 'package:ecotrap/core/usecases/usecase.dart' as _i12;
import 'package:ecotrap/features/wifi/domain/entities/wifi_network.dart' as _i7;
import 'package:ecotrap/features/wifi/domain/repositories/wifi_repository.dart'
    as _i2;
import 'package:ecotrap/features/wifi/domain/usecases/delete_wifi_network.dart'
    as _i10;
import 'package:ecotrap/features/wifi/domain/usecases/get_total_count.dart'
    as _i11;
import 'package:ecotrap/features/wifi/domain/usecases/get_wifi_networks.dart'
    as _i4;
import 'package:ecotrap/features/wifi/domain/usecases/save_wifi_network.dart'
    as _i8;
import 'package:ecotrap/features/wifi/domain/usecases/update_wifi_network.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWiFiRepository_0 extends _i1.SmartFake
    implements _i2.WiFiRepository {
  _FakeWiFiRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWiFiNetworks].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWiFiNetworks extends _i1.Mock implements _i4.GetWiFiNetworks {
  MockGetWiFiNetworks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WiFiRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWiFiRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WiFiRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.WiFiNetwork>>> call(
          _i4.GetWiFiNetworksParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.WiFiNetwork>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.WiFiNetwork>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.WiFiNetwork>>>);
}

/// A class which mocks [SaveWiFiNetwork].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWiFiNetwork extends _i1.Mock implements _i8.SaveWiFiNetwork {
  MockSaveWiFiNetwork() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WiFiRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWiFiRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WiFiRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WiFiNetwork>> call(
          _i8.SaveWiFiNetworkParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.WiFiNetwork>>.value(
            _FakeEither_1<_i6.Failure, _i7.WiFiNetwork>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.WiFiNetwork>>);
}

/// A class which mocks [UpdateWiFiNetwork].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateWiFiNetwork extends _i1.Mock implements _i9.UpdateWiFiNetwork {
  MockUpdateWiFiNetwork() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WiFiRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWiFiRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WiFiRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WiFiNetwork>> call(
          _i9.UpdateWiFiNetworkParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.WiFiNetwork>>.value(
            _FakeEither_1<_i6.Failure, _i7.WiFiNetwork>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.WiFiNetwork>>);
}

/// A class which mocks [DeleteWiFiNetwork].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteWiFiNetwork extends _i1.Mock implements _i10.DeleteWiFiNetwork {
  MockDeleteWiFiNetwork() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WiFiRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWiFiRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WiFiRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetTotalCount].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTotalCount extends _i1.Mock implements _i11.GetTotalCount {
  MockGetTotalCount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WiFiRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWiFiRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WiFiRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, int>> call(_i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, int>>.value(
            _FakeEither_1<_i6.Failure, int>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, int>>);
}
